package com.wcs.base.exception.message;

import java.io.Serializable;

/**
 * Simple message object that just contains a String already formatted
 * and localized.
 * 
 * @author Chris Guan
 */
public class ExceptionStringMessage implements Serializable, ExceptionMessage
{

   private static final long serialVersionUID = 2L;

   /**
    * The string version of the message. This is only used when the original
    * message from a wrapped exception is being used. Since it is already
    * localized, it will simply be stored here and used as the message.
    */
   private String message;

   /**
    * <p>
    * Creates a new exception message initialized to a static message. Use this
    * only for messages generated by third-party software, i.e., those which do
    * not use enumerated message keys.
    * </p>
    * 
    * @param message the static message
    */
   public ExceptionStringMessage(String message)
   {
      // This will not be further localized
      this.message = message;
   }

   /* (non-Javadoc)
    */
   public String getAsString()
   {
      return message;
   }
}
